### ISSUE TITLE
[frontend] display room objects

### ISSUE THREAD

**Issue by lunaticcoding** [lunaticcoding/SpbRoomApp#4]
# TODO's
- [ ] display all room objects
- [ ] search for room 
- [ ] sort by status

# Format
- see #3 

# Details
