### ISSUE TITLE
Dokument Django stuff for Alex

### ISSUE THREAD

**Issue by lunaticcoding** [lunaticcoding/SpbRoomApp#8]
# TODO's 
- [ ] how to run locally 
- [ ] how to access admin area
- [ ] endpoints -> all responses, what is expected
